import{a as k,i as l,S as f}from"./assets/vendor-CkdzJWux.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const p=s=>s.map(({webformatURL:e,largeImageURL:a,tags:o,likes:t,views:r,comments:n,downloads:S})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${e}" alt="${o}" />
        </a>
        <div class="thumb-block">
          <div class="block"><h2 class="title">Likes</h2><p class="amount">${t}</p></div>
          <div class="block"><h2 class="title">Views</h2><p class="amount">${r}</p></div>
          <div class="block"><h2 class="title">Comments</h2><p class="amount">${n}</p></div>
          <div class="block"><h2 class="title">Downloads</h2><p class="amount">${S}</p></div>
        </div>
      </li>`).join(""),q="49342840-003e2c292237fbf09de0074d9",z="https://pixabay.com/api/";async function y(s,e=1){var a,o;try{return(await k.get(z,{params:{key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data}catch(t){throw new Error(((o=(a=t.response)==null?void 0:a.data)==null?void 0:o.message)||"Failed to fetch images")}}function b(){const s=document.querySelectorAll(".gallery-item"),e=["size-small","size-wide","size-tall"];s.forEach(a=>{a.classList.forEach(t=>{t.startsWith("size-")&&a.classList.remove(t)});const o=e[Math.floor(Math.random()*e.length)];a.classList.add(o)})}const L=document.querySelector(".form"),h=document.querySelector(".gallery"),g=document.querySelector(".loader"),i=document.querySelector(".btn2");let c=1,m="";const v=20;g.style.display="none";i.classList.add("is-hidden");function w(){g.style.display="block"}function d(){g.style.display="none"}function u(s){const e=s?'linear-gradient(rgba(46, 47, 66, 0.8), rgba(46, 47, 66, 0.8)), url("/img/1.webp")':'linear-gradient(rgba(46, 47, 66, 0.3), rgba(46, 47, 66, 0.3)), url("/img/1.webp")';document.body.style.backgroundImage=e,console.log("Background set to:",e)}async function M(s){if(s.preventDefault(),h.innerHTML="",w(),i.classList.add("is-hidden"),m=s.target.elements["search-text"].value.trim(),c=1,!m){l.error({title:"Error",message:"Input cannot be empty!",color:"#ff0000"}),d();return}try{const e=await y(m,c);if(d(),!e.hits.length){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),u(!1);return}h.innerHTML=p(e.hits),b(),u(!0),new f(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}).refresh(),e.totalHits>c*v&&i.classList.remove("is-hidden"),L.reset()}catch(e){d(),l.error({title:"Error",message:e.message}),u(!1)}}async function E(s){w(),c++;try{const e=await y(m,c);d(),(!e.hits.length||e.hits.length<v)&&(i.classList.add("is-hidden"),i.removeEventListener("click",E),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),h.insertAdjacentHTML("beforeend",p(e.hits)),b(),u(!0),new f(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}).refresh()}catch(e){d(),l.error({title:"Error",message:e.message}),u(!1)}}L.addEventListener("submit",M);i.addEventListener("click",E);
//# sourceMappingURL=index.js.map
